Add director
AndreySabitov/java-filmorate pull request #10
Opened 2024-10-24 14:44 UTC by Pavel7947

2024-10-24 15:00 UTC, Pavel7947 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        return findAll(GET_FILMS_BY_DIRECTOR + orderBy, dirId);
Не знаю конкатенация в таких случаях нормальное решение или нет. Просто если делать через подстановочных символ появляется исключение о том что Spring не может преобразовать в нужный тип данных. И запрос не отправляется.

2024-10-24 15:01 UTC, Pavel7947 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        return findAll(GET_FILMS_BY_DIRECTOR + orderBy, dirId);
Почитал в интернете разные статьи увидел что так делают и решил сделать также

2024-10-24 15:07 UTC, Pavel7947 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        return findAll(GET_FILMS_BY_DIRECTOR + orderBy, dirId);
Еще сначала хотел сделать выбор порядка сортировки через enum но это получается довольно замороченный код.  В итоге не стал делать, показалось в этом нет особого смысла.

2024-10-24 15:09 UTC, Pavel7947 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        return findAll(GET_FILMS_BY_DIRECTOR + orderBy, dirId);
Ну и в основном старался конечно подстроиться под существующий код. Свои хотелки я лучше где нибудь в другом месте реализую.

2024-10-24 16:05 UTC, PancakeNM commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        return findAll(GET_FILMS_BY_DIRECTOR + orderBy, dirId);
Так и надо делать, ты здесь не сможешь использовать String.format, а подстановочный символ только там используется

2024-10-25 06:40 UTC, AndreySabitov commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +        return getDirectorById(id);
Думаю можно возвращать просто director.setId(id)

2024-10-25 06:40 UTC, AndreySabitov commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +        return getDirectorById(director.getId());
А тут просто return director

2024-10-25 06:40 UTC, AndreySabitov commented on src/main/resources/schema.sql
> +   film_id INTEGER REFERENCES films(film_id),
Нужно добавить ON DELETE CASCADE, чтобы вручную таблицы не чистить

2024-10-25 06:40 UTC, AndreySabitov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        directorDbStorage.deleteDirectorOfFilm(filmId);
Если есть ON DELETE CASCADE то вручную не нужно чистить. Я свои методы тоже удалю

2024-10-25 06:40 UTC, AndreySabitov commented on src/main/resources/data.sql
> +INSERT INTO directors (director_name)
Не совсем понимаю зачем нужно предзаполнение

2024-10-25 06:40 UTC, AndreySabitov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/director/DirectorDbStorage.java
> +        delete(DELETE_DIRECTOR_QUERY, dirId);
Если в БД есть фильм, который ссылается на данного режиссёра, то получается что удаление не произойдёт. Думаю можно это обработать

2024-10-25 07:58 UTC, Pavel7947 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/director/DirectorDbStorage.java
> +        delete(DELETE_DIRECTOR_QUERY, dirId);
Как я понял мне нужно поставить on delete cascade на оба поля таблицы films_directors. Тогда все само удалится

2024-10-25 08:20 UTC, AndreySabitov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/director/DirectorDbStorage.java
> +        delete(DELETE_DIRECTOR_QUERY, dirId);
Да, точно

2024-10-25 11:47 UTC, PancakeNM commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +        return getDirectorById(id);
Согласен с Андреем, здесь лучше сделать возврат передаваемого объекта, просто присвоить ему id через сеттер

2024-10-25 11:47 UTC, PancakeNM commented on src/main/java/ru/yandex/practicum/filmorate/service/DirectorService.java
> +        return getDirectorById(id);
при том присваивать id очень желательно внутри самого хранилища

2024-10-25 12:15 UTC, PancakeNM requested changes
В целом работоспособность в норме, нужно только некоторые моменты подправить

2024-10-25 12:15 UTC, PancakeNM commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private void setGenresMpaAndDirectors(Film film) {
И этот метод желательно перенести внутрь хранилища, как и всю логику присвоения полей, в сервисе должны остаться только вызовы методов хранилища и валидация

2024-10-25 12:15 UTC, PancakeNM commented on src/main/resources/data.sql
> +INSERT INTO directors (director_name)
Жанры предзаполнять нужно точно

2024-10-25 12:15 UTC, PancakeNM commented on src/main/resources/data.sql
> +VALUES ('Woody Allen'), ('Billy Wilder'), ('Quentin Jerome Tarantino');
Не нужно предзаполнять директоров, в тестах постмана реализовано добавление набора тестовых директоров в отличии от жанров

2024-10-25 12:31 UTC, AndreySabitov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private void setGenresMpaAndDirectors(Film film) {
Не понимаю чем хуже этот метод, если он в сервисе

2024-10-25 12:59 UTC, PancakeNM commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private void setGenresMpaAndDirectors(Film film) {
Данные меньше защищены от изменений сейчас. Вся работа с данными должна происходить внутри хранилища

2024-10-25 13:01 UTC, PancakeNM commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private void setGenresMpaAndDirectors(Film film) {
Сервис должен производить только валидацию и передачу в методы хранилища приходящих данных

2024-10-25 13:04 UTC, PancakeNM commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private void setGenresMpaAndDirectors(Film film) {
а тут мы имеем ситуацию, когда на уровне сервиса можно подменить значение полей, которые устанавливаются в этом методе. Дыра получается.

2024-10-25 14:59 UTC, AndreySabitov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private void setGenresMpaAndDirectors(Film film) {
можешь какую - нибудь статью дать на эту тему?

2024-10-25 15:27 UTC, PancakeNM commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private void setGenresMpaAndDirectors(Film film) {
щас искал статью, и понял, что я не прав, этот метод может оставаться тут впринципе, но я бы все равно его переименовал. 

Вот ссылка на статью: https://habr.com/ru/articles/531106/

2024-10-25 17:05 UTC, PancakeNM approved these changes

2024-10-26 07:18 UTC, AndreySabitov approved these changes

2024-10-26 07:23 UTC, merged